#!/bin/bash

if [ ! -d target ] || [ ! -f classpath.txt ]
then
	mvn clean package
	mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt
fi

RWS_CP=target/classes:`cat classpath.txt`
RWS_HOSTNAME=`hostname -f`

nohup java \
    -Djava.endorsed.dirs=target/endorsed \
    -Djava.net.preferIPv4Stack=true \
    -Xmx1024m \
    -cp $RWS_CP \
    eu.wisebed.restws.WisebedRestServer \
    --hostname $RWS_HOSTNAME \
    --logLevel DEBUG \
    --port 8080 \
    --testbedMap testbedMap.json \
    --webAppRootDir ../wisegui \
    2>&1 >> /dev/null &
    
echo $! >> rest-ws.pid
