#!/bin/bash

if [ ! -d target ] || [ ! -f classpath.txt ]
then
	mvn clean package
	mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt
fi

nohup java -Djava.endorsed.dirs=target/endorsed -Djava.net.preferIPv4Stack=true -Xmx1024m -cp target/classes:`cat classpath.txt` eu.wisebed.restws.WisebedRestServer --hostname `hostname -f` --logLevel DEBUG --port 8080 --testbedMap testbedMap.json 1> rest-ws.out 2> rest-ws.err &
