#!/bin/bash

git pull origin master && \
mvn clean package -DskipTests && \
mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt && \
java -Djava.endorsed.dirs=target/endorsed -Djava.net.preferIPv4Stack=true -Xmx1024m -cp target/classes:`cat classpath.txt` eu.wisebed.restws.WisebedRestServer --hostname `hostname -f` --logLevel DEBUG --port 8080 --testbedMap testbedMap.json
