package eu.wisebed.restws.jobs;

public enum JobType {

	ARE_NODES_ALIVE,
	DESTROY_VIRTUAL_LINK,
	DISABLE_NODE,
	DISABLE_PHYSICAL_LINK,
	ENABLE_NODE,
	ENABLE_PHYSICAL_LINK,
	FLASH_PROGRAMS,
	RESET_NODES,
	SEND,
	SET_CHANNEL_PIPELINE,
	SET_VIRTUAL_LINK,
}